PREFIX : <https://www.example.org/foot#>

SELECT (?name AS ?player) (COUNT(DISTINCT ?euro) AS ?count_euros)
WHERE
{
  ?id_participation :player ?id_player; :euro ?euro.
  ?id_player :name ?name.
}
GROUP BY ?name
ORDER BY DESC(?count_euros)
