PREFIX : <https://www.example.org/foot#>

SELECT (?name AS ?player) (SUM(?matches) AS ?total_matches)
WHERE {
  ?id_participation :player ?id_player; :matches ?matches.
  ?id_player :name ?name.
}
GROUP BY ?name
HAVING (?total_matches >= 1)
ORDER BY DESC(?total_matches)
