PREFIX : <https://www.example.org/foot#>

SELECT (?name AS ?player) (SUM(COALESCE(?goals,0)) AS ?total_goals) (SUM(COALESCE(?matches,0)) AS ?total_matches)
WHERE {
  ?id_participation :player ?id_player.
  ?id_player :name ?name.
  OPTIONAL{?id_participation :goals ?goals. } 
  OPTIONAL{?id_participation :matches ?matches. }             

}
GROUP BY ?name
HAVING (?total_goals > 0)
ORDER BY DESC(?total_goals) DESC(?total_matches)
