PREFIX : <https://www.example.org/foot#>

SELECT DISTINCT ?player ?euro1 ?goals1 ?euro2 ?goals2
WHERE {
  ?id_participation1 :player ?id_player; :euro ?euro1; :goals ?goals1.
  ?id_participation2 :player ?id_player; :euro ?euro2; :goals ?goals2.
  FILTER (?euro1 < ?euro2)
  ?id_player :name ?player.
}
ORDER BY ?euro1 DESC(?player)